apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
        - 10.50.99.0/24
    - name: static
      protocol: layer2
      addresses:
        - 10.50.100.0/24
      auto-assign: false
